package com.skillissue.roastapp.provider;

import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;

@Component
public class CannedProvider implements RoastProvider {

    private final Map<String, List<String>> canned = Map.of(
            "SDE", List.of(
                    "You call yourself a Software Development Engineer, but your GitHub contribution graph looks like a crime scene photo. Green squares are rarer than your interview callbacks. You LeetCode like you're allergic to correctness — O(n²) solutions with the confidence of someone who's never heard of Big O. Your mom still tells the neighbors you 'build the internet,' completely unaware you spent today Googling what a hash map actually is. Recruiters who somehow still talk to you spend more time laughing than reading, and honestly, so does your mom, once she sees your code.",
                    "You think 'System Design' means drawing three boxes and an arrow labeled 'magic happens here.' Your idea of scaling a system is closing more Chrome tabs. Somewhere, a whiteboard is having nightmares about you and requesting a transfer. You've been 'grinding DSA' for eight months and still can't invert a binary tree without crying a little — your mom couldn't invert it either, but at least she's not lying about it to her book club. Your confidence in interviews is inversely proportional to your actual code quality, which is genuinely impressive on its own.",
                    "You call bugs 'undocumented features' and hope nobody notices, the same way your mom calls the burnt casserole 'artisanal.' Your commit messages are just 'fix' repeated forty times like a diary of quiet suffering. If confidence shipped code, you'd be a FAANG principal engineer by now — instead you're stuck debugging a for-loop since Tuesday, blaming the compiler. Your pull requests get more red squiggly lines than a toddler's homework, and your reviewer has started leaving comments in the tone usually reserved for group project members who vanish entirely.",
                    "Your idea of 'clean code' is code that compiles, which is a low bar you still routinely fail to clear. You've rewritten the same to-do app six times and called each one a breakthrough. Your mom keeps telling the neighbors you're 'basically a hacker,' which is technically true if hacking means guessing Stack Overflow answers until one works. You describe yourself as a 'problem solver,' but the only problem you've solved recently is figuring out which streaming service to cancel first. Somewhere, a compiler is filing a restraining order against you.",
                    "You treat Big O notation like a rumor rather than something you're responsible for knowing. Your recursive functions don't have base cases, they have vibes and a prayer. Somewhere your mom is telling her book club you 'work with computers,' unaware you spent today Googling what a hash map is for the third time this month. Your code reviews take longer than your actual coding sessions, mostly because everyone's trying to figure out how to say 'this is wrong' six different polite ways before giving up and just writing 'please see me.'",
                    "Your idea of testing is running it once, seeing no red text, and calling it production-ready. You've never met an edge case you didn't personally introduce, usually by accident, sometimes twice. Your mom still asks if you've 'fixed the internet yet,' and honestly the internet is safer with you nowhere near it. Your understanding of Big O ends at 'O for oh no,' which is at least an accurate emotional description of your last three sprints. Somewhere, a null pointer exception is naming its firstborn after you out of gratitude.",
                    "You've memorized exactly one sorting algorithm and use it for every single problem, including ones that clearly need a graph traversal. Your mom thinks 'merge conflict' is something that happens at family dinners, and given how you handle Git, she's more qualified to resolve one than you are. You call every bug a 'feature under investigation' and every crash 'expected behavior in edge environments.' Your standup updates are 45% jargon, 45% stalling, and 10% something that might, generously, be interpreted as actual progress on the ticket.",
                    "Your understanding of concurrency is 'I ran two terminals at once and nothing exploded, so we're good.' You've caused three race conditions this month and named none of them, because acknowledging them would mean fixing them. Your mom brags that you 'debug computers for a living,' unaware that yesterday you spent four hours debugging a typo in a variable name. You once called a memory leak 'just how the app breathes.' Somewhere, your own code is quietly leaking memory and judging you for it.",
                    "You've read 'Cracking the Coding Interview' exactly zero times but you've watched 30 YouTube videos summarizing it, which you consider equivalent. Your mom asks what a 'linked list' is and you can't actually explain it either, so you both just nod and change the subject. Your idea of optimization is deleting comments to make the file smaller. You once refactored a function by renaming a variable and called it a 'major architecture improvement' in the sprint retro, and somehow nobody stopped you.",
                    "Your git blame history reads like a true crime documentary, and you're the recurring suspect in every episode. You've force-pushed to main more times than you've written unit tests, which is to say, more than zero. Your mom still doesn't understand why you 'need a whole computer just to make a button,' and frankly, watching your last three PRs, neither do your teammates. You call every merge conflict 'a learning experience,' which is your way of saying you still don't understand Git."
            ),
            "Data Analyst", List.of(
                    "You put 'proficient in SQL' everywhere but you still write SELECT * and pray. Your dashboards have more misleading pie charts than a conspiracy theorist's PowerPoint. You call it 'data storytelling' — everyone else calls it guessing with extra steps. Your mom asks what a pivot table is and honestly your explanation would confuse her more than the actual concept. You've presented the same insight three times because nobody remembers what you said the first two, mostly because it wasn't true either time.",
                    "You 'clean data' the way toddlers clean their rooms — shove everything under the rug and call it done. Your Excel formulas are held together with hope and VLOOKUP errors nobody's brave enough to fix. Your mom thinks you 'do math for a job,' unaware your actual job today was figuring out why a spreadsheet says negative twelve people bought a positive number of items. Stakeholders read your reports and immediately schedule a meeting to un-confuse themselves, which somehow you also get invited to.",
                    "You think correlation implies causation and you will die on that hill, alone, with a chart nobody asked for. Your idea of statistical rigor is eyeballing a trendline and vibing hard. Your mom's horoscope readings have a higher hit rate than your quarterly forecasts, and she's not even trying. Every insight you've ever presented could've been replaced by a Magic 8-Ball with better accuracy and a shorter meeting. You call this 'data-driven decision making' with a completely straight face.",
                    "You've used Python for exactly one thing: importing pandas and immediately Googling the rest. Your A/B tests have sample sizes smaller than your LinkedIn network, which itself is not large. Confidence intervals? You're not even confident in your own conclusions, let alone the math behind them. Your mom asks what you actually do all day and you've started saying 'data stuff' because the real answer takes too long and ends badly for everyone involved, including the data.",
                    "You call yourself 'data-driven' but your decisions are 90% gut feeling and 10% a chart you didn't fully understand. Your pivot tables pivot away from the truth more reliably than they pivot the data. Your mom still thinks Excel and 'the internet' are the same thing, and honestly your reports haven't done much to correct her. You've built a dashboard so confusing that even you need someone else to explain it to you in the next meeting.",
                    "Your idea of a 'deep dive' into the data is scrolling down the spreadsheet once and closing the tab. You've never met an outlier you didn't just quietly delete and hope nobody asked about. Your mom thinks 'null value' is a type of insult, and given how often you use it to explain your own missing analysis, she's not entirely wrong. Your monthly report has the same three conclusions every single month, just rearranged to look like new insight.",
                    "You've presented a chart with no axis labels in front of actual leadership and called it 'clean design.' Your SQL joins are less joins and more hostage negotiations that end badly for the database. Your mom asks if you're 'good with computers' and you've started just saying 'sort of,' which is the most honest performance review you've given yourself all year. You once described a completely flat trendline as 'showing strong momentum,' and somehow got a follow-up meeting scheduled.",
                    "Your dashboards load slower than your mom's dial-up internet from 2003, and produce roughly the same amount of useful information. You've never once double-checked a number before putting it in a slide, which explains a lot about last quarter's 'forecast.' You call every unexplained spike in the data 'seasonality' even in months that don't have seasons. Somewhere, a stakeholder is quietly building their own spreadsheet because they've stopped trusting yours entirely, and honestly, fair.",
                    "You think 'big data' just means a really wide spreadsheet, and you refuse further questions on the topic. Your mom asks why you need three monitors just to look at numbers, and you don't actually have a good answer for her either. Your regression models regress mostly your own confidence, one failed p-value at a time. You've called a completely random pattern 'a clear emerging trend' in at least four separate all-hands meetings this year alone.",
                    "Your idea of forecasting is copying last month's number and adding five percent, then calling it 'modeling.' You've never once been asked to explain your methodology twice, because the first explanation already made everyone regret asking. Your mom still introduces you as someone who 'works with Excel,' and at this point that's more accurate than your actual job title. Somewhere, a real data scientist just felt a disturbance, sighed, and went back to labeling training data."
            ),
            "Full Stack Engineer", List.of(
                    "You call yourself full-stack but your CSS looks like it was designed during an earthquake. Your backend is a single Express route doing the job of twelve microservices, held together by console.logs you forgot to remove. 'It works on my machine' is basically your love language at this point. Your mom asks why the app you built 'looks broken,' and you've stopped being able to explain that it's actually supposed to look like that, mostly because it isn't.",
                    "Your frontend has more div soup than a homeless shelter kitchen, and somehow less structure. You center a div and call it a personality trait worth putting on LinkedIn. Your API returns 200 OK even when it fails, because accountability was never part of the stack you learned. Your mom clicked your deployed site once and it crashed, and you've told her it was 'just a server thing' four separate times since, hoping she'd stop asking.",
                    "You've 'built' six to-do list apps and zero things anyone's ever actually used, including your own family. Your idea of state management is fifteen useState hooks fighting each other in the dark, unsupervised. Your deployment process is 'push to main and pray to the Vercel gods' every single time, with no exceptions. Your mom asked if your app is 'like the real Instagram,' and the honest answer made you close your laptop for the rest of the night.",
                    "You claim you 'know React' but you still don't understand why your component re-renders forty times a second under normal use. Your Git history is a graveyard of commits titled 'final,' 'final final,' and 'actually final this time I promise.' Your mom thinks a 'component' is a part of the TV remote, and honestly her mental model of your code is more coherent than your actual code. Users don't rage-quit your app — they just quietly never come back, ever.",
                    "Your database schema looks like it was designed by throwing darts at a whiteboard blindfolded, during a small earthquake. You've never met a null pointer you didn't personally, lovingly create. 'Full-stack' should legally require a permit after what you've done to that backend this quarter alone. Your mom asked if she could 'see the website you made' and you had to explain that it only works if you personally restart the server first, every single time.",
                    "You wrote a REST API with zero consistent naming, so half your endpoints are plural and half are singular, apparently by mood. Your CORS errors have their own dedicated Slack channel at this point, with a pinned message just for you. Your mom thinks 'the cloud' is where your website lives, and honestly that's more understanding than you've shown of your own hosting setup this month. You once fixed a bug by refreshing the page and called it 'resolved in prod.'",
                    "Your idea of responsive design is making the font smaller and hoping mobile users don't complain too loudly. You've hardcoded so many pixel values that your layout breaks the moment anyone resizes a window even slightly. Your mom tried your site on her phone and the button was literally unclickable, and you told her it's 'a known issue,' which is generous phrasing for 'I never once tested this.' Somewhere, a UX designer just felt real physical pain.",
                    "You've shipped an app with the admin password still hardcoded in the frontend JavaScript, visible to literally anyone who opens dev tools. Your mom doesn't know what dev tools are, which honestly makes her safer online than your actual paying users right now. You call this 'MVP thinking,' security team calls it 'an incident report waiting to happen.' You once fixed a production outage by turning the server off and on again and celebrated like it was a real engineering win.",
                    "Your idea of testing in production is watching Sentry errors roll in and calling it 'real-time monitoring.' You've broken the build on main four times this sprint, twice on the exact same line, in the exact same way. Your mom asked what 'full-stack' means and you gave an answer so vague she now thinks you might not actually have a real job. Somewhere, your own staging environment has quietly given up trying to match production at all.",
                    "You copy-pasted a UI library's example code directly into production and never once read what it actually does under the hood. Your webpack config is a black box even you're afraid to open, let alone explain to anyone else on the team. Your mom asked if your website is 'done yet' and you've been saying 'almost' for eight months straight now, with no end genuinely in sight. Somewhere, a senior engineer reviewing your PR just quietly closed their laptop."
            ),
            "AI Engineer", List.of(
                    "You call yourself an AI Engineer but you've never trained anything more complex than your patience for reading documentation. Your 'custom model' is just a ChatGPT wrapper with a fancier README and a worse rate limit. You say 'fine-tuning' in conversations and hope nobody asks a real follow-up question about it. Your mom thinks you 'built a robot,' and you've let her believe that for eight months now because the truth felt more embarrassing.",
                    "Your understanding of transformers begins and ends with a YouTube thumbnail that said 'Attention Is All You Need,' and you never actually read the paper past the title. You've called three different things 'AI' this week alone, and none of them involved a single gradient update. Your mom asked how 'the AI' works and your explanation was somehow vaguer than the actual research, which is genuinely a feat. Your resume has more buzzwords than your model has parameters.",
                    "You think prompt engineering is a personality trait now, and you bring it up unprompted at family dinners. Your 'RAG pipeline' is a for-loop and a prayer duct-taped to an API call. You've hallucinated more confidence in interviews than your model ever has in production, which is genuinely saying something. Your mom thinks you talk to computers for a living, and watching your actual output, it's honestly more like the computer's carrying the conversation for you.",
                    "You use 'leverage LLMs' in every sentence like it's a magic spell that replaces actual understanding of anything at all. Your embeddings are cosine-similarity-searched into oblivion because you genuinely don't know what else to do with them. Your mom asked what a 'vector database' is and your answer made her more confused about databases in general, which took real effort. Somewhere, an actual ML researcher just felt a disturbance and quietly closed their laptop in secondhand embarrassment.",
                    "You call GPU cost optimization 'not my department' and mean it with your whole chest, unbothered. Your model overfits harder than you oversold your own skills on your last application. You've read the phrase 'attention mechanism' more times than you've actually implemented one, and it shows in every conversation. Your mom thinks you're building 'the next ChatGPT,' and you've stopped correcting her because the real explanation takes too long and ends somewhere sadder.",
                    "You've called a basic if-else statement 'a decision-making AI system' in an actual client presentation and nobody stopped you. Your temperature setting is always maxed out because you think 'creative' means 'the model just makes things up now, whatever.' Your mom asked if the AI 'has feelings' and honestly your prompt engineering has less structure than that question deserves. You once debugged a hallucination by just telling the model 'please don't lie' in the system prompt.",
                    "Your idea of evaluation is asking the model if its own answer 'seems right' and taking its word for it completely. You've deployed a chatbot that confidently recommends completely made-up sources, and called that a 'known limitation' in the docs. Your mom asked if you tested it before shipping, and you changed the subject faster than your model changes facts. Somewhere, a real evaluator is quietly building a benchmark specifically to catch people exactly like you.",
                    "You think context window size is a personality flex you bring up unprompted in every single conversation, technical or not. Your token budget management is 'send everything and hope,' repeated indefinitely across every single request. Your mom doesn't understand what 'context window' means, but somehow neither do you, based on how your bill looked last month. You've called an obvious hallucination 'creative interpretation' in a client-facing Slack message, and hit send before thinking twice.",
                    "You've fine-tuned exactly one model, on a dataset of forty examples, and you now introduce yourself as someone who 'does ML research' at parties. Your evaluation metric is vibes, occasionally cross-checked against your own mood that day. Your mom asked if your AI could 'help her write emails' and it confidently invented a meeting that never happened, then apologized in a tone somehow more professional than yours. You called that incident 'a minor edge case.'",
                    "You describe every single project as 'AI-powered,' including the one that's just an if-statement checking a boolean value. Your system prompt is eleven paragraphs long and the model still ignores half of it completely. Your mom asked what you actually built and you said 'an AI,' the same non-answer you've given every relative for over a year now. Somewhere, your own model is quietly generating a better explanation of your job than you've ever managed to."
            ),
            "ML Engineer", List.of(
                    "You call yourself an ML Engineer but your model's confusion matrix is less confused than you are about your own career right now. You've overfit every model you've ever trained and undertrained every skill you actually need for the job. Your mom thinks you 'teach computers,' and given your validation accuracy lately, the computers might be teaching you more. Your loss curve goes down; your credibility, notably, does not follow it downward or up.",
                    "Your idea of hyperparameter tuning is changing the learning rate once and hoping for the best like it's a slot machine at 2am. You've deployed exactly zero models to production but you've got 'MLOps' proudly listed on your resume anyway. Your mom asked what 'overfitting' means and your explanation described your own job search more accurately than any model you've built. Your validation accuracy is the only thing you've never actually validated properly.",
                    "You still don't know the difference between precision and recall but you'll happily explain 'AI ethics' to anyone who'll listen at a party. Your feature engineering is just throwing every column in and letting XGBoost sort out your mess. Your mom thinks you 'build robots that think,' and honestly your last model's decision boundary makes about as much sense as that description does. You call that a pipeline; everyone else, correctly, calls it duct tape.",
                    "You trained a model for six hours and called it a day when it hit 51% accuracy — a coin flip does better and doesn't need a GPU or your six hours. Your Jupyter notebook has 200 cells and zero of them run in order anymore, by anyone, including you. Your mom asked if the model 'works now' and you said 'define works,' which is genuinely the most honest thing you've said all week. You've cited 'data drift' for problems that were always just your code.",
                    "Your idea of model interpretability is shrugging and saying 'it's a black box' to literally every single question asked. You've copy-pasted more Kaggle notebooks than you've written original code in your entire career so far. Your mom asked what your model actually predicts and you gave an answer so vague she assumed you were changing the subject on purpose. Somewhere, a decision tree is quietly embarrassed to be associated with you at all.",
                    "You call every failed experiment 'exploratory analysis' and every successful one 'proof of concept,' regardless of what actually happened. Your training data has more duplicate rows than your explanation has original ideas in any given meeting. Your mom asked if you 'taught the computer to be smart' and honestly your last model's F1 score suggests the computer taught itself despite you being there. You've never once looked at a confusion matrix without visibly flinching first.",
                    "Your idea of cross-validation is running it once and hoping the number looks believable enough to screenshot for the slide deck. You've deployed a model that predicts the majority class every single time and called it 'a strong baseline' in the report. Your mom asked what accuracy means and your explanation somehow made the concept less clear than it was before you opened your mouth. You once blamed a bug in your evaluation script on 'noisy data' for three weeks straight.",
                    "You think regularization is something you'll 'get to eventually,' the same way you've said that about writing actual unit tests for two years running. Your model's predictions have more variance than your mood during a live demo in front of stakeholders. Your mom asked if the AI 'learned' anything and you said 'sort of,' which was also your answer about learning Git properly three years ago. Somewhere, a loss function is quietly refusing to converge just for you specifically.",
                    "You've named every single model 'model_final' and then created a 'model_final_v2' the very next day without irony or self-awareness. Your GPU utilization graph looks like a heart monitor flatlining, occasionally spiking when you remember the job is running at all. Your mom asked if you're 'good at math' and your model's calibration curve says, gently but firmly, no. You've called a completely untuned baseline 'production-ready' in an actual sprint review meeting.",
                    "Your idea of MLOps is manually re-running a notebook every Monday morning and calling that 'the pipeline' with a straight face. You've never once set up proper versioning, so nobody, including you, actually knows which model is currently live in production right now. Your mom asked what happens if the model breaks and you said 'it hasn't yet,' the same energy as ignoring a check-engine light for six months. Somewhere, a real MLOps engineer just felt genuine, deep pain."
            ),
            "Cloud Engineer", List.of(
                    "You call yourself a Cloud Engineer but your last AWS bill made the finance team schedule an emergency meeting, with you specifically named in the invite. You've left three EC2 instances running since March because you were 'pretty sure' you'd need them again eventually. Your mom asked what 'the cloud' actually is and your explanation made her more confused about computers in general, which took real effort on your part.",
                    "You set every S3 bucket to public 'just to test something quickly' and then simply never went back to fix it, not once. Your VPC diagram looks like a subway map drawn during actual turbulence, by someone who's never seen a subway. Your mom thinks 'the cloud' is where your files live, and honestly that's more understanding than you've shown of your own network setup all year. You've said 'it's probably a networking issue' about literally every single bug you've personally caused.",
                    "Your Kubernetes cluster has more crash loops than a toddler learning to walk for the very first time, unsupervised. You copy-paste Terraform from Stack Overflow and pray the apply doesn't nuke production on a Friday specifically. Your mom asked if you 'fixed the cloud yet' and you didn't have the energy to explain that clouds don't break, only your configuration of them does, repeatedly, this week alone.",
                    "You've never once successfully set up CI/CD without breaking the pipeline for everyone else, specifically on a Friday afternoon, every single time. Your load balancer configuration has load-balanced exactly zero load in its entire deployed lifetime so far. Your mom asked what your job actually involves and 'yelling at YAML files' was, embarrassingly, the most accurate answer you had available. Somewhere, a security team is quietly crying about your IAM permissions right now.",
                    "You think 'the cloud' just means someone else's problem now, and you've made that abundantly clear in every single incident postmortem you've written. Your Linux skills begin and end with sudo and blind, unearned hope that it'll just work this time. Your mom asked if you're 'good with computers' and your last outage's root-cause analysis suggests, gently, that the answer is genuinely unclear even to you. You've restarted a server as your first, second, and only troubleshooting step for two years running now.",
                    "Your idea of disaster recovery is 'we'll figure it out when it happens,' said with the calm of someone who's never actually lived through an outage. You've hardcoded an API key directly into a public repo and only noticed when GitHub emailed you about it, three days later. Your mom asked if 'the internet' could actually break and you had to explain that yes, and also, specifically, sometimes it's you personally breaking it.",
                    "You've provisioned a database with public access enabled 'temporarily' back in January, and it is, notably, still January energy in your security posture. Your Terraform state file has been manually edited so many times it's basically a diary of your worst decisions this year. Your mom asked what 'infrastructure' means and honestly your own infrastructure can't answer that question reliably either, most days, including today.",
                    "Your monitoring dashboard has 40 alerts configured and you've muted all of them because they were 'too noisy' to actually deal with properly. You found out about last week's outage from a customer tweet, not from any of the tooling you personally set up and maintain. Your mom asked if you'd know if something broke and the honest answer, based on recent history, is genuinely no, not really, not reliably.",
                    "You've deployed the same misconfigured security group to three different environments because copy-paste felt faster than actually understanding it. Your idea of cost optimization is closing the billing dashboard tab so you don't have to look at the number anymore. Your mom asked how much your company spends on 'the cloud thing' and you changed the subject faster than an autoscaling group under real load, genuinely faster.",
                    "Your runbooks are eight months out of date and reference a service that got decommissioned back in the spring without your knowledge. You once resolved a production incident by SSHing directly into the box and editing a config file live, and called that 'a quick fix' in the postmortem. Your mom asked if you're 'in charge of the internet' at your company and the honest, slightly terrifying answer is: unsupervised, apparently yes, for now."
            )
    );


    @Override
    public String generateRoast(String role, Map<String, Integer> ratings, int percentage) {
        List<String> options = canned.getOrDefault(role, List.of("No roast available for this role."));
        int index = ThreadLocalRandom.current().nextInt(options.size());
        return options.get(index);
    }
}